;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/_FPS_Portfolio/Blueprints/Enemies/Data/DT_States.DT_States
+GameplayTagTableList=/Game/_FPS_Portfolio/Blueprints/Enemies/GameplayTags/DT_EnemyAI.DT_EnemyAI
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Ammo.Color.Yello",NewTagName="Ammo.Color.Yellow")
+GameplayTagRedirects=(OldTagName="Button.Event.OpenDoor",NewTagName="Button.Event.Red")
+GameplayTagRedirects=(OldTagName="Button.Event.RemoveWall",NewTagName="Button.Event.Blue")
+GameplayTagRedirects=(OldTagName="Button.Event.SpawnPickup",NewTagName="Button.Event.Green")
+GameplayTagRedirects=(OldTagName="Button.Event.TogglePlatform",NewTagName="Button.Event.Yellow")
+GameplayTagList=(Tag="Ammo.Color.Attacking",DevComment="")
+GameplayTagList=(Tag="Ammo.Color.Blue",DevComment="")
+GameplayTagList=(Tag="Ammo.Color.Green",DevComment="")
+GameplayTagList=(Tag="Ammo.Color.Red",DevComment="")
+GameplayTagList=(Tag="Ammo.Color.Yellow",DevComment="")
+GameplayTagList=(Tag="AmmoData.AmmoColorTag",DevComment="")
+GameplayTagList=(Tag="Button.Event.Blue",DevComment="")
+GameplayTagList=(Tag="Button.Event.Green",DevComment="")
+GameplayTagList=(Tag="Button.Event.Red",DevComment="")
+GameplayTagList=(Tag="Button.Event.Yellow",DevComment="")
+GameplayTagList=(Tag="Chase",DevComment="")
+GameplayTagList=(Tag="Investigate",DevComment="")
+GameplayTagList=(Tag="Patrol",DevComment="")

